service: problems

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  profile: tymian
  environment:
    PROBLEM_TABLE: ${self:service}-${self:provider.stage}
    CATEGORY_TABLE: categories-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:DescribeLogGroups
        - logs:DescribeLogStreams
        - logs:PutLogEvents
        - logs:GetLogEvents
        - logs:FilterLogEvents
      Resource: "*"

resources:
  Resources:
    ProblemDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "ProblemId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "ProblemId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.PROBLEM_TABLE}
    CategoryDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "CategoryId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "CategoryId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CATEGORY_TABLE}

functions:
  createProblem:
    handler: api/problem/create.createProblem
    memorySize: 128
    description: Create new problem
    events:
      - http:
          path: api/problems
          method: post
  listProblems:
    handler: api/problem/list.listProblems
    memorySize: 128
    description: List all problems
    events:
      - http:
          path: api/problems
          method: get
  getProblem:
    handler: api/problem/get.getProblem
    memorySize: 128
    events:
      - http:
          path: api/problems/{id}
          method: get
  deleteProblem:
    handler: api/problem/delete.deleteProblem
    memorySize: 128
    events:
      - http:
          path: api/problems/{id}
          method: delete
  updateProblem:
    handler: api/problem/update.updateProblem
    memorySize: 128
    events:
      - http:
          path: api/problems/{id}
          method: patch
  createCategory:
    handler: api/category/create.createCategory
    memorySize: 128
    description: Create new category
    events:
      - http:
          path: api/categories
          method: post
  listCategories:
    handler: api/category/list.listCategories
    memorySize: 128
    description: List all categories
    events:
      - http:
          path: api/categories
          method: get
  getCategory:
    handler: api/category/get.getCategory
    memorySize: 128
    events:
      - http:
          path: api/categories/{id}
          method: get
  deleteCategory:
    handler: api/category/delete.deleteCategory
    memorySize: 128
    events:
      - http:
          path: api/categories/{id}
          method: delete
  updateCategory:
    handler: api/category/update.updateCategory
    memorySize: 128
    events:
      - http:
          path: api/categories/{id}
          method: patch
